### ISSUE TITLE
Issue in generating python code from .fidl file

### ISSUE THREAD

**Issue by Siddharthav1** [gunnarx/pyfrancagen#1]
Hi,

I’m trying to generate code from a certain .fidl file that has a method ‘sayHello’ defined in it. I placed the .fidl file in the /lbs/fidl directory.

I am using pyfrancagen to generate codes which I would then be making use for to make method calls from my client side to a c++ server.

 The .fidl file is as shown in below:

```
package commonapi
  
interface HelloWorld {
  version {major 1 minor 0}
  method sayHello {
    in {
      String name
    }
    out {
      String message
    }
  }
  
    broadcast Mystatus {
        out {
            String available
        }
    }
}
```

Made the following changes in the generate_lbs.py file as shown in snapshot 1:

![image](https://user-images.githubusercontent.com/59814967/87918377-f6edbc00-ca93-11ea-8189-4876de89f817.png)

**Fig 2. Snapshot 1**

On trying the following commands given in the readme.md file (Snapshot 2) I have been getting the following error:

![image](https://user-images.githubusercontent.com/59814967/87918412-04a34180-ca94-11ea-9d79-797e7ffdceb5.png)

**Fig 3. Snapshot 2**

The detailed error is as below:

```
shru@shru-VirtualBox:~/Documents/PythonSomeIP/Work/pyfranca_test/pyfrancagen/lbs$ ./generate_lbs.py
-------------------------------------------------------
 ----- PROCESSING ../lbs/fidl/HelloWorld.fidl -----
-------------------------------------------------------
../lbs/fidl/HelloWorld.fidl
Traceback (most recent call last):
  File "./generate_lbs.py", line 23, in <module>
    main()
  File "./generate_lbs.py", line 19, in main
    process_file(f)
  File "/home/shru/Documents/PythonSomeIP/Work/pyfranca_test/pyfrancagen/lbs/../pyfranca_cpp/pyfranca_cpp.py", line 154, in process_file
    process_fidl(f, fidl_text)
  File "/home/shru/Documents/PythonSomeIP/Work/pyfranca_test/pyfrancagen/lbs/../pyfranca_cpp/pyfranca_cpp.py", line 165, in process_fidl
    template_render_plain_file(processor, ['interfaces'], template, ".h")
  File "/home/shru/Documents/PythonSomeIP/Work/pyfranca_test/pyfrancagen/lbs/../pyfranca_cpp/pyfranca_cpp.py", line 355, in template_render_plain_file
    tpl = env.get_template(templatefile)
  File "/home/shru/Documents/PythonSomeIP/Work/pyfranca_test/pyfrancagen/lbs/../jinja/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/shru/Documents/PythonSomeIP/Work/pyfranca_test/pyfrancagen/lbs/../jinja/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/shru/Documents/PythonSomeIP/Work/pyfranca_test/pyfrancagen/lbs/../jinja/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/shru/Documents/PythonSomeIP/Work/pyfranca_test/pyfrancagen/lbs/../pyfranca_cpp/pyfranca_cpp.py", line 48, in get_source
    with file(path) as f:
```

I have the following questions:

 1. Does the pyfrangen tool generate python codes with respect to the fidl file fed the same way how the common api c++ code generators do? 
       
 2. Can the generated codes then be used in other .py files to make function/method calls just like how the code generated by common api code generators can be used at the c++ server and client side. Please elaborate a little more on how to generated codes can be made use of.

 3. As shown in snapshot 3 there are a few errors while running the generate_lbs.py file. There were a few syntax errors which I could correct by myself. But I’m unable to correct the error shown in Snapshot3. 
I’m currently using python3.8. Are the errors I’m getting due to mismatch in the python version in which generate_lbs was written in? 

 4. Which version of python is used in pyfrancagen tool? I will also use the same version to avoid any sort of compatibility issues.

 Also, kindly let me know if there are any more steps to be followed other than the one mentioned in the readme.md file to be able to generate code.

Kindly help me solve this issue. Thanks in advance.

Regards,
Siddhartha V

**Comment by gunnarx** [comment]
Hi!  As you noticed, I haven't answered this for almost 2 years. I never saw the notification that you had asked a question, and the project was not a priority.  I am answering now mostly to close this issue, and as information to anyone else that is interested.  (The new PRs #2 #3 #4 show there is some interest by someone)

First of all, remember that this project was more an example of what is possible than any usable product.  It was something intended to build upon / build from.   As you can see, it has also not been updated since 2017, and it is not a priority for me.

Originally I created a **C++** output, not python, and used it only for one thing:  To run Doxygen document generator on the output in order to get a "nice" HTML documentation from the Franca code.   There are probably many other approaches to take nowadays.
Of course, I could then imagine the _possibility_ to use it for other purposes but it did not progress beyond a proof-of-concept at that time.

>  Does the pyfrangen tool generate python codes with respect to the fidl file fed the same way how the common api c++ code generators do?

No, it is called **pyfrancagen** because it was based on **pyfranca**.  **pyfranca** is probably called **pyfranca** because itself is written in python (but only the original author of pyfranca should know this).

As it stands it generates a basic C++ code structure.  What it generates is driven from the template files.  You could make your own templates to generate something else, like python, but to be honest you would write a new code generator as well, because the logic is _very_ specific to the needs of the C++ code at the moment.  This should be very evident when looking at the (complicated) code in [pyfranca_cpp.py](https://github.com/gunnarx/pyfrancagen/blob/master/pyfranca_cpp/pyfranca_cpp.py)

> Can the generated codes then be used in other .py files to make function/method calls just like how the code generated by common api code generators can be used at the c++ server and client side. Please elaborate a little more on how to generated codes can be made use of.

No, I'm afraid not.  See above.

> As shown in snapshot 3 there are a few errors while running the generate_lbs.py file. There were a few syntax errors which I could correct by myself. But I’m unable to correct the error shown in Snapshot3.

I can't quite figure out what the error is from that, but since the project does not do what you are looking for anyway (and since it is 2 years later...) I conclude that it is not worth putting time into investigating.

> I’m currently using python3.8. Are the errors I’m getting due to mismatch in the python version in which generate_lbs was written in?

Yes, probably, as #2 now indicates.
