### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by Rosi2143** [gunnarx/pyfrancagen#5]
Hi @gunnarx,

I would like to use this [pyfrancagen](https://github.com/gunnarx/pyfrancagen) project - with the changes in the 3 pull requests
* #2 
* #3 
* #4 
in our projects.

It would be great if you can add a license file.

Thanks.

**Comment by gunnarx** [comment]
Sure thing.  MPLv2 OK for you?

**Comment by gunnarx** [comment]
I took a look at it and most of the subdirectories had their own licenses already, including the Franca interfaces.  Only the code inside lbs/ might have been uncertain.  There shouldn't be a LICENSE file in the root directory since it only pulls together multiple projects, some of which are not mine.   Anyhow, I pushed a bit of update now - see latest commit.

**Comment by gunnarx** [comment]
Also, I wrote a long comment in #1 that might interest you.

**Comment by Rosi2143** [comment]
Hi @gunnarx,

thanks. I think it is OK - for our OSS guys - with the new [License ](https://github.com/gunnarx/pyfrancagen/blob/master/lbs/LICENSE) file. I did not want to re-use [pyfranca_cpp.py](https://github.com/gunnarx/pyfrancagen/blob/master/pyfranca_cpp/pyfranca_cpp.py) without your permission :-).
And MPLv2 is definately OK.

I will raise further PR's when we find more improvements. But currently it works like a charm and the generator allows us to easily extend our code.

Thanks.
